### ISSUE TITLE
Expose MarkdownButtonElement in public API

### ISSUE THREAD

**Issue by tobscure** [github/markdown-toolbar-element#5]
Thanks for open-sourcing this great little lib.

Would it be possible to expose the MarkdownButtonElement class in the public API so that it can be extended to implement custom buttons.

My use-case is actually to implement buttons for BBCode (`[b][/b]`, `[code][/code]`, `[*]`, etc), given that the functionality provided by the MarkdownButtonElement provides a very good foundation for this.

Would be happy to send a PR for this, but unsure of the best way to do so given that the style definitions are stored in a private WeakMap. Thoughts?

**Comment by muan** [comment]
This sounds like a good idea! I haven't have the time to look into it yet though. Let me get back to you. If you have an idea in the mean time feel free to send a PR too.

**Comment by tobscure** [comment]
On further thought, the ideal would actually be to expose the `styleSelectedText` function so that you can take advantage of the great logic and `StyleArgs` API from any context (not just special button elements). How do you feel about that?

In terms of exposing `MarkdownButtonElement`, I guess `styles` could just be set as an instance property instead of a WeakMap?

**Comment by koddsson** [comment]
Hi @tobscure 👋 Thanks for the issue.

Me and @muan looked at how it would look if we somehow supported other styles via multiple methods and came to the conclusion that since we are probably never going to support anything other than Markdown, we probably don't want to support any other use cases at this time since it would add complexity to what we are trying to keep as a simple custom element.

I think the best course of action in order to support BBCode would be to fork `github/markdown-toolbar-element` and replace the markdown syntax with BBCode syntax. You could still receive updates from the upstream project but you'd just have to make sure that conflicts are resolved (they should resolve cleanly if you just change the markdown strings to BBCode).

Thanks again for the issue

**Comment by sinanisler** [comment]
+1
